// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CursorService exposes mouse control to the frontend. Every exported
 * method becomes a typed, promise-returning function in the JS bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DoubleClick performs a double left click at the current cursor position.
 */
export function DoubleClick(): $CancellablePromise<void> {
    return $Call.ByID(230731018);
}

/**
 * GetCursorPosition returns the current absolute cursor position.
 */
export function GetCursorPosition(): $CancellablePromise<[number, number]> {
    return $Call.ByID(2392912616);
}

/**
 * GetScreenSize returns the desktop bounds used to map hand positions to pixels.
 */
export function GetScreenSize(): $CancellablePromise<$models.Screen> {
    return $Call.ByID(3936759500);
}

/**
 * LeftClick performs a left click at the current cursor position.
 */
export function LeftClick(): $CancellablePromise<void> {
    return $Call.ByID(2630670190);
}

/**
 * MouseDown holds the left button down (start of a drag).
 */
export function MouseDown(): $CancellablePromise<void> {
    return $Call.ByID(319160538);
}

/**
 * MouseUp releases the left button (end of a drag).
 */
export function MouseUp(): $CancellablePromise<void> {
    return $Call.ByID(2981662015);
}

/**
 * MoveCursor moves the cursor to an absolute position on the virtual desktop.
 */
export function MoveCursor(x: number, y: number): $CancellablePromise<void> {
    return $Call.ByID(3017236268, x, y);
}

/**
 * MoveCursorRelative moves the cursor by a pixel delta (used while dragging).
 */
export function MoveCursorRelative(dx: number, dy: number): $CancellablePromise<void> {
    return $Call.ByID(3213107708, dx, dy);
}

/**
 * RightClick performs a right click at the current cursor position.
 */
export function RightClick(): $CancellablePromise<void> {
    return $Call.ByID(3199507269);
}

/**
 * Scroll rotates the wheel. Positive = up, negative = down.
 */
export function Scroll(delta: number): $CancellablePromise<void> {
    return $Call.ByID(1024745574, delta);
}

/**
 * SetAlwaysOnTop toggles whether the control window floats above other apps
 * so the camera keeps tracking while you use other windows.
 */
export function SetAlwaysOnTop(on: boolean): $CancellablePromise<void> {
    return $Call.ByID(2291618924, on);
}

/**
 * SetWindowSize resizes the control window (used by the compact mode toggle).
 */
export function SetWindowSize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(3347564492, width, height);
}
