// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Screen describes the usable desktop area (the union of all monitors).
 */
export interface Screen {
    /**
     * origin of the virtual desktop (can be negative)
     */
    "X": number;
    "Y": number;

    /**
     * total width in pixels
     */
    "Width": number;

    /**
     * total height in pixels
     */
    "Height": number;

    /**
     * true on macOS (origin is bottom-left)
     */
    "FlippedY": boolean;
}
